parameters:
    admin_email: null
    admin_name: admin
    mailer_transport: smtp
    mailer_host: 127.0.0.1
    mailer_user: null
    mailer_password: null
    locale: en
    secret: janus
    security.authentication.manager.erase_credentials: false
    database_driver:   pdo_mysql
    database_host:     127.0.0.1
    database_port:     ~
    database_name:     janus
    database_user:     root
    database_password: ~
    database_prefix: janus__


