imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

framework:
    #esi:             ~
    translator:      { fallback: "%locale%" }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        assets_version: 1234
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:      ~
        cookie_secure:   true
        cookie_httponly: true
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [ ]
    filters:
        cssrewrite: ~
        less:
            node: /usr/bin/node
            node_paths: [/usr/lib/node_modules]
            apply_to: "\.less$"
        uglifyjs2:
            bin: /usr/bin/uglifyjs
            apply_to: "\.js$"
        uglifycss:
            bin: /usr/bin/uglifycss
            apply_to: "\.css$"
    variables:
        locale: [en, nl]

# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

monolog:
    channels: ["metadata"]
    handlers:
        mail:
            type:         fingers_crossed
            action_level: critical
            handler:      buffered
        buffered:
            type:    buffer
            handler: swift
        swift:
            type:       swift_mailer
            from_email: no-reply@surfnet.nl
            to_email:   "%error_mail_address%"
            subject:    "%error_mail_subject%"
            level:      debug
        metadata:
            type:     stream
            path:     "%kernel.logs_dir%/metadata.log"
            level:    debug
            channels: metadata

norzechowicz_ace_editor:
    base_path: "https://rawgit.com/ajaxorg/ace-builds/master"

doctrine_cache:
    providers:
        my_memcached_cache:
            memcached:
                servers: %memcached_servers%
            namespace: prod
            alias: cache
        metadata:
            file_system:
                directory: %kernel.root_dir%/data/metadata/
            alias: cache.metadata

braincrafted_bootstrap:
    output_dir: compiled
    jquery_path: js/jquery.min.js
    icon_prefix: fa
    fonts_dir: %kernel.root_dir%/../web/compiled/fonts
    customize:
        variables_file: %kernel.root_dir%/Resources/less/variables.less

knp_menu:
    providers:
        builder_alias: false

apy_data_grid:
    pagerfanta:
        enable: true
        view_class: Pagerfanta\View\TwitterBootstrap3View

stof_doctrine_extensions:
    orm:
        default:
            timestampable: true

lexik_translation:
    fallback_locale: en
    managed_locales: [en,nl]

stfalcon_tinymce:
    tinymce_jquery: true
    language: %locale%
    theme:
        simple:
            theme: "modern"
            menubar: false
            toolbar: "bold italic underline | bullist numlist outdent indent | link"
            plugins:
                - "autolink lists link contextmenu paste"

exercise_html_purifier:
    default:
        Attr.AllowedFrameTargets: "_blank"
