services:

    parser:
        class: AppBundle\Metadata\Parser
        arguments: [@guzzle.client]

    validator.metadata:
        class: AppBundle\Validator\Constraints\ValidMetadataValidator
        arguments: [@parser]
        tags:
            - { name: validator.constraint_validator, alias: metadata }

    validator.certificate:
        class: AppBundle\Validator\Constraints\ValidSSLCertificateValidator
        arguments: [@guzzle.client]
        tags:
            - { name: validator.constraint_validator, alias: certificate }

    subscription.manager:
        class: AppBundle\Manager\SubscriptionManager
        arguments: [@doctrine.orm.entity_manager, @validator, @lock.manager]

    lock.manager:
        class: AppBundle\Manager\LockManager
        arguments: [@cache, @session]
