services:

    cert.fetcher:
        class: AppBundle\Metadata\CertificateFetcher
        arguments: [@cache]

    cert.parser:
        class: AppBundle\Metadata\CertificateParser

    fetcher:
        class: AppBundle\Metadata\Fetcher
        arguments: [@guzzle.client, @cache, @monolog.logger.metadata]

    parser:
        class: AppBundle\Metadata\Parser
        arguments: [@fetcher, @cert.parser, %kernel.root_dir%/Resources/schemas/, @cache, @monolog.logger.metadata]

    generator:
        class: AppBundle\Metadata\Generator
        arguments: [@fetcher, @cache.metadata, @monolog.logger.metadata]

    validator.metadata:
        class: AppBundle\Validator\Constraints\ValidMetadataValidator
        arguments: [@parser]
        tags:
            - { name: validator.constraint_validator, alias: metadata }

    validator.certificate:
        class: AppBundle\Validator\Constraints\ValidSSLCertificateValidator
        arguments: [@cert.fetcher, @cert.parser]
        tags:
            - { name: validator.constraint_validator, alias: certificate }

    subscription.manager:
        class: AppBundle\Manager\SubscriptionManager
        arguments: [@doctrine.orm.entity_manager, @validator, @lock.manager, @generator, @event_dispatcher]

    lock.manager:
        class: AppBundle\Manager\LockManager
        arguments: [@cache, @session]

    mail.manager:
        class: AppBundle\Manager\MailManager
        arguments: [@mailer, @templating, @translator, '%mail_from%', '%mail_receiver%']

    menu_builder:
        class: AppBundle\Menu\MenuBuilder
        arguments: ["@knp_menu.factory"]

    menu:
        class: Knp\Menu\MenuItem
        factory_service: menu_builder
        factory_method: createAdminMenu
        arguments: ["@request"]
        scope: request
        tags:
            - { name: knp_menu.menu, alias: menu }

    twig.database_loader:
        class: AppBundle\Twig\DatabaseLoader
        arguments: [ @doctrine.orm.entity_manager, @cache ]
        tags:
            - { name: twig.loader }

    validator.twig:
        class: AppBundle\Validator\Constraints\ValidTwigTemplateValidator
        arguments: [@twig]
        tags:
            - { name: validator.constraint_validator, alias: twig_template }

    listener.security:
        class: AppBundle\EventListener\SimpleSAMLAuthListener
        tags:
            - { name: kernel.event_listener, event: kernel.controller, method: onKernelController }

    form.transformer.html_purifier:
        class: Exercise\HTMLPurifierBundle\Form\HTMLPurifierTransformer
        arguments: [@exercise_html_purifier.default]

    form.type.purified_textarea:
        class: AppBundle\Form\Admin\Type\PurifiedTextareaType
        arguments: [@form.transformer.html_purifier]
        tags:
            - { name: form.type, alias: purified_textarea }

    validator.mapping.cache.cache:
        class: Symfony\Component\Validator\Mapping\Cache\DoctrineCache
        arguments: [@cache]
