services:

    cert.fetcher:
        class: AppBundle\Metadata\CertificateFetcher
        arguments: [@cache]

    cert.parser:
        class: AppBundle\Metadata\CertificateParser

    parser:
        class: AppBundle\Metadata\Parser
        arguments: [@guzzle.client, @cert.parser, @cache, %kernel.root_dir%/Resources/schemas/]

    validator.metadata:
        class: AppBundle\Validator\Constraints\ValidMetadataValidator
        arguments: [@parser]
        tags:
            - { name: validator.constraint_validator, alias: metadata }

    validator.certificate:
        class: AppBundle\Validator\Constraints\ValidSSLCertificateValidator
        arguments: [@cert.fetcher, @cert.parser]
        tags:
            - { name: validator.constraint_validator, alias: certificate }

    subscription.manager:
        class: AppBundle\Manager\SubscriptionManager
        arguments: [@doctrine.orm.entity_manager, @validator, @lock.manager]

    lock.manager:
        class: AppBundle\Manager\LockManager
        arguments: [@cache, @session]

    mail.manager:
        class: AppBundle\Manager\MailManager
        arguments: [@mailer, @templating, @translator, '%mail_from%', '%mail_receiver%']

    menu_builder:
        class: AppBundle\Menu\MenuBuilder
        arguments: ["@knp_menu.factory"]

    menu:
        class: Knp\Menu\MenuItem
        factory_service: menu_builder
        factory_method: createAdminMenu
        arguments: ["@request"]
        scope: request
        tags:
            - { name: knp_menu.menu, alias: menu }

    twig.database_loader:
        class: AppBundle\Twig\DatabaseLoader
        arguments: [ @doctrine.orm.entity_manager ]
        tags:
            - { name: twig.loader }

    validator.twig:
        class: AppBundle\Validator\Constraints\ValidTwigTemplateValidator
        arguments: [@twig]
        tags:
            - { name: validator.constraint_validator, alias: twig_template }

    listener.security:
        class: AppBundle\EventListener\SimpleSAMLAuthListener
        tags:
            - { name: kernel.event_listener, event: kernel.controller, method: onKernelController }
