---
- name: Add group {{ support_fpm_user }}
  group: name={{ support_fpm_user }} state=present

- name: Add user {{ support_fpm_user }}
  user: name={{ support_fpm_user }} group={{ support_fpm_user }} createhome=no state=present

- name: Create SSL key
  copy: content="{{ https_dev_star_private_key }}" dest={{ tls.cert_private_path }}/star.{{ base_domain  }}.key mode=0600 owner=root
  when: certs_sp_dashboard

- name: Create SSL certificate
  copy: src=files/certs/star.{{ base_domain }}.pem dest="{{ tls.cert_path }}/star.{{ base_domain}}.pem"
  when: certs_sp_dashboard

- name: Copy ca file
  copy: src=files/certs/star.{{ base_domain}}_ca.pem dest={{tls.cert_path_ca}}/star.{{ base_domain}}_ca.pem
  register: copy ca_file
  notify: update_ca_trust
  when: certs_sp_dashboard

- name: Install Apache vhosts
  template:
    src: '{{ item }}.j2'
    dest: /etc/httpd/conf.d/{{ item }}
  with_items:
    - support.conf
  notify:
    - reload httpd

- name: php-fpm config
  template:
    src: '{{ item }}.j2'
    dest: /etc/php-fpm.d/{{ item }}
  with_items:
     - support-pool.conf
  notify:
    - reload php-fpm

- name: Remove ssl.conf
  file:
    path: /etc/httpd/conf.d/ssl.conf
    state: absent
  notify:
    - reload httpd

- name: Add hosts file
  lineinfile:
    path: /etc/hosts
    state: present
    line: '127.0.0.1 dev.support.surfconext.nl engine.dev.support.surfconext.nl serviceregistry.dev.support.surfconext.nl mujina-idp.dev.support.surfconext.nl mujina-sp.dev.support.surfconext.nl engine-api.dev.support.surfconext.nl'

- name: Create symfony database
  mysql_db: name=symfony state=present
