---
- name: Add group {{ support_fpm_user }}
  group: name={{ support_fpm_user }} state=present

- name: Add user {{ support_fpm_user }}
  user: name={{ support_fpm_user }} group={{ support_fpm_user }} createhome=no state=present

- name: Create SSL key
  copy: content="{{ https_star_private_key }}" dest={{ tls.cert_private_path }}/star.{{ base_domain  }}.key mode=0600 owner=root
  when: develop

- name: Create SSL certificate
  copy: src=files/certs/star.{{ base_domain }}.pem dest="{{ tls.cert_path }}/star.{{ base_domain}}.pem"
  when: develop

- name: Copy ca file
  copy: src=files/certs/star.{{ base_domain}}_ca.pem dest={{tls.cert_path_ca}}/star.{{ base_domain}}_ca.pem
  register: copy ca_file
  notify: update_ca_trust
  when: develop

- name: Install Apache vhosts
  template:
    src: '{{ item }}.j2'
    dest: /etc/httpd/conf.d/{{ item }}
  with_items:
    - support.conf
  notify:
    - reload httpd

- name: php-fpm config
  template:
    src: '{{ item }}.j2'
    dest: /etc/php-fpm.d/{{ item }}
  with_items:
     - support-pool.conf
  notify:
    - reload php-fpm

