---
- hosts: all
  become: true
  roles:
    - ../OpenConext-deploy/roles/openconext-common
    - ../OpenConext-deploy/roles/httpd
    - ../OpenConext-deploy/roles/php56fpm
    - ../OpenConext-deploy/roles/mysql
    - ../OpenConext-deploy/roles/janus
    - spform
